use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::io::{self, IsTerminal, Read, Write};
use std::path::PathBuf;
use std::process::{Command, Output, Stdio};

use clap::{Args, Parser, Subcommand, ValueEnum};
use serde::Serialize;
use serde_json::json;
use toml::Value as TomlValue;

const DEFAULT_CONFIG_PATH: &str = "~/.config/zt/config.toml";
const CONFIG_ENV: &str = "ZT_CONFIG";
const DEFAULT_REMOTE_PATH: &str =
    "/opt/homebrew/bin:/usr/local/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH";
const NEW_MARKER: &str = "+ new session";
const VERSION: &str = env!("CARGO_PKG_VERSION");

const KNOWN_COMMANDS: &[&str] = &[
    "browse",
    "b",
    "config",
    "install",
    "setup",
    "bootstrap",
    "local",
    "here",
    "l",
    "remote",
    "there",
    "r",
    "list",
    "ls",
    "status",
    "doctor",
    "exists",
    "ensure",
    "attach",
    "a",
    "new",
    "n",
    "kill",
    "k",
    "close",
    "delete",
    "d",
    "rm",
];

const AFTER_HELP: &str = r#"human examples:
  zt local                   attach/create local session 'main'
  zt remote                  attach/create remote session 'main'
  zt local work              attach/create local session 'work'
  zt remote work             attach/create remote session 'work'
  zt local new               attach/create an autogenerated local session
  zt remote new              attach/create an autogenerated remote session
  zt remote --auto           attach/create an autogenerated remote session
  zt                         browse remote sessions on tmm
  zt main                    remote shorthand for session 'main'
  zt auto                    remote shorthand for an autogenerated session
  zt --mosh remote main      attach/create remote session over mosh
  zt --picker prompt         browse with numbered prompt
  zt config init             write ~/.config/zt/config.toml
  zt install                 install missing local/remote dependencies

agent/noninteractive examples:
  zt list --json             list active sessions as JSON
  zt status --json           check local/remote dependencies
  zt config show --json      print effective config
  zt install --dry-run --json
  zt install --yes --json
  zt exists main --json      return 0 if active, 1 if missing
  zt ensure main --json      create detached session if missing
  zt attach --auto --background --json
  zt attach main --background --json
  zt close main --missing-ok --json
  zt delete main --missing-ok --json

environment:
  ZT_CONFIG=~/.config/zt/config.toml ZT_HOST=tmm ZT_TRANSPORT=ssh ZT_PICKER=auto"#;

#[derive(Debug)]
struct ZtError {
    message: String,
    code: i32,
}

impl ZtError {
    fn new(message: impl Into<String>, code: i32) -> Self {
        Self {
            message: message.into(),
            code,
        }
    }
}

impl From<io::Error> for ZtError {
    fn from(value: io::Error) -> Self {
        Self::new(value.to_string(), 1)
    }
}

type ZtResult<T> = Result<T, ZtError>;

#[derive(Clone, Debug, Eq, PartialEq)]
enum Transport {
    Ssh,
    Mosh,
}

impl Transport {
    fn parse(value: &str) -> ZtResult<Self> {
        match value.trim().to_ascii_lowercase().as_str() {
            "ssh" => Ok(Self::Ssh),
            "mosh" => Ok(Self::Mosh),
            _ => Err(ZtError::new("transport must be one of: mosh, ssh", 2)),
        }
    }

    fn as_str(&self) -> &'static str {
        match self {
            Self::Ssh => "ssh",
            Self::Mosh => "mosh",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum Picker {
    Auto,
    Fzf,
    Prompt,
    None,
}

impl Picker {
    fn parse(value: &str) -> ZtResult<Self> {
        match value.trim().to_ascii_lowercase().as_str() {
            "auto" => Ok(Self::Auto),
            "fzf" => Ok(Self::Fzf),
            "prompt" | "numbered" => Ok(Self::Prompt),
            "none" | "off" => Ok(Self::None),
            _ => Err(ZtError::new(
                "picker must be one of: auto, fzf, prompt, numbered, none",
                2,
            )),
        }
    }

    fn as_str(&self) -> &'static str {
        match self {
            Self::Auto => "auto",
            Self::Fzf => "fzf",
            Self::Prompt => "prompt",
            Self::None => "none",
        }
    }
}

#[derive(Clone, Debug)]
struct Config {
    host: String,
    transport: Transport,
    picker: Picker,
    remote_path: String,
    connect_timeout: u64,
    ssh_options: Vec<String>,
    no_input: bool,
    config_path: PathBuf,
    config_loaded: bool,
}

impl Config {
    fn defaults() -> Self {
        Self {
            host: "tmm".to_string(),
            transport: Transport::Ssh,
            picker: Picker::Auto,
            remote_path: DEFAULT_REMOTE_PATH.to_string(),
            connect_timeout: 10,
            ssh_options: Vec::new(),
            no_input: false,
            config_path: default_config_path(),
            config_loaded: false,
        }
    }
}

#[derive(Parser, Debug)]
#[command(
    name = "zt",
    version = VERSION,
    about = "Remote Zellij session manager for humans and automation.",
    after_help = AFTER_HELP
)]
struct Cli {
    #[arg(long, global = true, help = "config file path")]
    config: Option<String>,

    #[arg(short = 'H', long, global = true, help = "remote SSH host")]
    host: Option<String>,

    #[arg(
        long,
        global = true,
        help = "remote PATH used before invoking zellij/mosh/tmux"
    )]
    remote_path: Option<String>,

    #[arg(
        long,
        global = true,
        help = "SSH connect timeout in seconds, 0 disables the option"
    )]
    connect_timeout: Option<u64>,

    #[arg(
        long = "ssh-option",
        global = true,
        action = clap::ArgAction::Append,
        help = "extra ssh -o option, repeatable, e.g. --ssh-option UserKnownHostsFile=/tmp/known_hosts"
    )]
    ssh_options: Vec<String>,

    #[arg(
        long,
        global = true,
        value_enum,
        help = "interactive picker: auto, fzf, prompt, or none"
    )]
    picker: Option<PickerArg>,

    #[arg(long, global = true, help = "fail instead of opening fzf or prompts")]
    no_input: bool,

    #[arg(long, global = true, conflicts_with = "mosh", help = "attach over ssh")]
    ssh: bool,

    #[arg(long, global = true, conflicts_with = "ssh", help = "attach over mosh")]
    mosh: bool,

    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
enum PickerArg {
    Auto,
    Fzf,
    Prompt,
    Numbered,
    None,
    Off,
}

impl PickerArg {
    fn picker(self) -> Picker {
        match self {
            Self::Auto => Picker::Auto,
            Self::Fzf => Picker::Fzf,
            Self::Prompt | Self::Numbered => Picker::Prompt,
            Self::None | Self::Off => Picker::None,
        }
    }
}

#[derive(Subcommand, Debug)]
enum Commands {
    #[command(alias = "b", about = "interactively pick or create a session")]
    Browse,
    #[command(about = "inspect or create zt config")]
    Config(ConfigArgs),
    #[command(
        alias = "setup",
        alias = "bootstrap",
        about = "install missing local and remote dependencies"
    )]
    Install(InstallArgs),
    #[command(
        alias = "here",
        alias = "l",
        about = "attach/create a local Zellij session"
    )]
    Local(LocalArgs),
    #[command(
        alias = "there",
        alias = "r",
        about = "attach/create a session on the configured remote host"
    )]
    Remote(RemoteArgs),
    #[command(alias = "ls", about = "list active sessions")]
    List(ListArgs),
    #[command(alias = "doctor", about = "check local and remote dependencies")]
    Status(JsonArgs),
    #[command(about = "test whether an active session exists")]
    Exists(SessionJsonArgs),
    #[command(about = "create a detached session if it is missing")]
    Ensure(EnsureArgs),
    #[command(alias = "a", about = "attach to a session, creating it by default")]
    Attach(AttachArgs),
    #[command(alias = "n", about = "create/attach a session")]
    New(NewArgs),
    #[command(alias = "k", alias = "close", about = "close a running session")]
    Kill(MissingOkArgs),
    #[command(
        alias = "d",
        alias = "rm",
        about = "close and delete a session, including saved state"
    )]
    Delete(DeleteArgs),
}

#[derive(Args, Debug)]
struct ConfigArgs {
    #[command(subcommand)]
    command: Option<ConfigCommand>,
}

#[derive(Subcommand, Debug)]
enum ConfigCommand {
    #[command(about = "print config file path")]
    Path,
    #[command(about = "print effective config")]
    Show(JsonArgs),
    #[command(about = "write a starter config file")]
    Init(ConfigInitArgs),
}

#[derive(Args, Debug)]
struct ConfigInitArgs {
    #[arg(long, help = "overwrite an existing config file")]
    force: bool,
}

#[derive(Args, Debug)]
struct JsonArgs {
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
}

#[derive(Args, Debug)]
struct SessionJsonArgs {
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
}

#[derive(Args, Debug)]
struct InstallArgs {
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(
        long,
        conflicts_with = "remote_only",
        help = "only install local dependencies"
    )]
    local_only: bool,
    #[arg(
        long,
        conflicts_with = "local_only",
        help = "only install remote dependencies"
    )]
    remote_only: bool,
    #[arg(short = 'y', long, help = "run install commands without prompting")]
    yes: bool,
    #[arg(long, help = "print the install plan without running it")]
    dry_run: bool,
    #[arg(long, help = "install mosh locally and remotely")]
    with_mosh: bool,
    #[arg(long, help = "install tmux on the remote host")]
    with_tmux: bool,
    #[arg(long, help = "install zellij locally too")]
    with_local_zellij: bool,
    #[arg(long, help = "do not install local fzf")]
    no_fzf: bool,
}

#[derive(Args, Debug)]
struct LocalArgs {
    #[arg(
        default_value = "main",
        help = "Zellij session name (default: main; use new/auto/- for generated)"
    )]
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "generate a readable unique session name")]
    auto: bool,
    #[arg(short = 'b', long, help = "create detached session and do not attach")]
    background: bool,
    #[arg(long, help = "fail if the session does not already exist")]
    no_create: bool,
    #[arg(long, help = "print the command instead of running it")]
    print_command: bool,
}

#[derive(Args, Debug)]
struct RemoteArgs {
    #[arg(
        default_value = "main",
        help = "Zellij session name (default: main; use new/auto/- for generated)"
    )]
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "generate a readable unique session name")]
    auto: bool,
    #[arg(short = 'b', long, help = "create detached session and do not attach")]
    background: bool,
    #[arg(long, help = "fail if the session does not already exist")]
    no_create: bool,
    #[arg(long, help = "print the command instead of running it")]
    print_command: bool,
}

#[derive(Args, Debug)]
struct ListArgs {
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "print only the number of matching sessions")]
    count: bool,
    #[arg(long, help = "only include sessions starting with this prefix")]
    prefix: Option<String>,
    #[arg(long, help = "only include sessions containing this text")]
    contains: Option<String>,
    #[arg(long, help = "ask zellij for reverse creation order")]
    reverse: bool,
}

#[derive(Args, Debug)]
struct EnsureArgs {
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "print the ssh command instead of running it")]
    print_command: bool,
}

#[derive(Args, Debug)]
struct AttachArgs {
    #[arg(
        default_value = "main",
        help = "Zellij session name (default: main; use new/auto/- for generated)"
    )]
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "generate a readable unique session name")]
    auto: bool,
    #[arg(short = 'b', long, help = "create detached session and do not attach")]
    background: bool,
    #[arg(long, help = "fail if the session does not already exist")]
    no_create: bool,
    #[arg(long, help = "print the command instead of running it")]
    print_command: bool,
}

#[derive(Args, Debug)]
struct NewArgs {
    #[arg(
        default_value = "new",
        help = "Zellij session name (default: autogenerated)"
    )]
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "generate a readable unique session name")]
    auto: bool,
    #[arg(short = 'b', long, help = "create detached session and do not attach")]
    background: bool,
    #[arg(long, help = "print the command instead of running it")]
    print_command: bool,
}

#[derive(Args, Debug)]
struct MissingOkArgs {
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "exit 0 if the session is already missing")]
    missing_ok: bool,
}

#[derive(Args, Debug)]
struct DeleteArgs {
    session: String,
    #[arg(short = 'j', long, help = "print machine-readable JSON")]
    json: bool,
    #[arg(long, help = "only delete if the session is not running")]
    no_force: bool,
    #[arg(long, help = "exit 0 if the session is already missing")]
    missing_ok: bool,
}

#[derive(Clone, Debug, Serialize)]
struct ToolStatus {
    present: bool,
    path: Option<String>,
    version: Option<String>,
}

#[derive(Clone, Debug, Serialize)]
struct InstallEntry {
    scope: String,
    package_manager: String,
    packages: Vec<String>,
    command: String,
}

#[derive(Clone, Debug, Serialize)]
struct InstallPlan {
    host: String,
    transport: String,
    picker: String,
    scopes: Vec<String>,
    targets: BTreeMap<String, Vec<String>>,
    installed: BTreeMap<String, Vec<String>>,
    missing: BTreeMap<String, Vec<String>>,
    package_managers: BTreeMap<String, Option<String>>,
    plan: Vec<InstallEntry>,
}

fn main() {
    let args = normalize_shortcut(env::args().skip(1).collect());
    let cli = Cli::parse_from(std::iter::once("zt".to_string()).chain(args));

    match run(cli) {
        Ok(code) => std::process::exit(code),
        Err(error) => {
            eprintln!("zt: {}", error.message);
            std::process::exit(error.code);
        }
    }
}

fn run(cli: Cli) -> ZtResult<i32> {
    let config = build_config(&cli)?;

    match &cli.command {
        Some(Commands::Browse) => browse(&config),
        Some(Commands::Config(args)) => config_command(&config, args),
        Some(Commands::Install(args)) => install_dependencies(&config, args),
        Some(Commands::Local(args)) => {
            let session =
                resolve_session_name(&args.session, args.auto, "local", Some(&config.host));
            attach_local(
                &session,
                !args.no_create,
                args.background,
                args.json,
                args.print_command,
            )
        }
        Some(Commands::Remote(args)) => {
            let session =
                resolve_session_name(&args.session, args.auto, "remote", Some(&config.host));
            attach(
                &config,
                &session,
                !args.no_create,
                args.background,
                args.json,
                args.print_command,
            )
        }
        Some(Commands::List(args)) => {
            let sessions = filter_sessions(
                list_sessions(&config, args.reverse)?,
                args.prefix.as_deref(),
                args.contains.as_deref(),
            );
            if args.json {
                print_json(
                    &json!({"host": config.host, "sessions": sessions, "count": sessions.len()}),
                )?;
            } else if args.count {
                println!("{}", sessions.len());
            } else {
                for session in sessions {
                    println!("{session}");
                }
            }
            Ok(0)
        }
        Some(Commands::Status(args)) => status(&config, args.json),
        Some(Commands::Exists(args)) => {
            let exists = session_exists(&config, &args.session)?;
            if args.json {
                print_json(
                    &json!({"host": config.host, "session": args.session, "exists": exists}),
                )?;
            }
            Ok(if exists { 0 } else { 1 })
        }
        Some(Commands::Ensure(args)) => {
            ensure_session(&config, &args.session, args.json, args.print_command)
        }
        Some(Commands::Attach(args)) => {
            let session =
                resolve_session_name(&args.session, args.auto, "remote", Some(&config.host));
            attach(
                &config,
                &session,
                !args.no_create,
                args.background,
                args.json,
                args.print_command,
            )
        }
        Some(Commands::New(args)) => {
            let session =
                resolve_session_name(&args.session, args.auto, "remote", Some(&config.host));
            attach(
                &config,
                &session,
                true,
                args.background,
                args.json,
                args.print_command,
            )
        }
        Some(Commands::Kill(args)) => {
            kill_session(&config, &args.session, args.missing_ok, args.json)
        }
        Some(Commands::Delete(args)) => delete_session(
            &config,
            &args.session,
            !args.no_force,
            args.missing_ok,
            args.json,
        ),
        None => {
            if config.no_input || !io::stdin().is_terminal() || !io::stdout().is_terminal() {
                Err(ZtError::new(
                    "no command provided; use 'zt --help' for noninteractive commands",
                    2,
                ))
            } else {
                browse(&config)
            }
        }
    }
}

fn normalize_shortcut(argv: Vec<String>) -> Vec<String> {
    let options_with_values = [
        "-H",
        "--host",
        "--config",
        "--remote-path",
        "--connect-timeout",
        "--ssh-option",
        "--picker",
    ];
    let flags = ["--ssh", "--mosh", "--no-input", "-h", "--help", "--version"];
    let mut skip_next = false;

    for (index, arg) in argv.iter().enumerate() {
        if skip_next {
            skip_next = false;
            continue;
        }
        if arg == "--" {
            break;
        }
        if options_with_values.contains(&arg.as_str()) {
            skip_next = true;
            continue;
        }
        if options_with_values
            .iter()
            .any(|option| arg.starts_with(&format!("{option}=")))
        {
            continue;
        }
        if flags.contains(&arg.as_str()) || arg.starts_with('-') {
            continue;
        }
        if !KNOWN_COMMANDS.contains(&arg.as_str()) {
            let mut normalized = Vec::with_capacity(argv.len() + 1);
            normalized.extend_from_slice(&argv[..index]);
            normalized.push("attach".to_string());
            normalized.push(arg.clone());
            normalized.extend_from_slice(&argv[index + 1..]);
            return normalized;
        }
        return argv;
    }
    argv
}

fn build_config(cli: &Cli) -> ZtResult<Config> {
    let mut config = Config::defaults();
    if let Some(path) = &cli.config {
        config.config_path = expand_tilde(path);
    }

    let file_values = read_config_file(&config.config_path)?;
    config.config_loaded = !file_values.is_empty();
    apply_values(&mut config, &file_values)?;
    apply_values(&mut config, &env_config_values()?)?;

    if let Some(host) = &cli.host {
        apply_host(&mut config, host)?;
    }
    if let Some(remote_path) = &cli.remote_path {
        apply_remote_path(&mut config, remote_path)?;
    }
    if let Some(connect_timeout) = cli.connect_timeout {
        config.connect_timeout = connect_timeout;
    }
    if !cli.ssh_options.is_empty() {
        config.ssh_options = cli.ssh_options.clone();
    }
    if let Some(picker) = cli.picker {
        config.picker = picker.picker();
    }
    if cli.no_input {
        config.no_input = true;
    }
    if cli.mosh {
        config.transport = Transport::Mosh;
    } else if cli.ssh {
        config.transport = Transport::Ssh;
    }

    Ok(config)
}

fn default_config_path() -> PathBuf {
    env::var(CONFIG_ENV)
        .map(|value| expand_tilde(&value))
        .unwrap_or_else(|_| expand_tilde(DEFAULT_CONFIG_PATH))
}

fn expand_tilde(path: &str) -> PathBuf {
    if path == "~" {
        return env::var_os("HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from(path));
    }
    if let Some(rest) = path.strip_prefix("~/")
        && let Some(home) = env::var_os("HOME")
    {
        return PathBuf::from(home).join(rest);
    }
    PathBuf::from(path)
}

fn read_config_file(path: &PathBuf) -> ZtResult<BTreeMap<String, TomlValue>> {
    if !path.exists() {
        return Ok(BTreeMap::new());
    }
    let content = fs::read_to_string(path).map_err(|error| {
        ZtError::new(
            format!("could not read config file {}: {error}", path.display()),
            2,
        )
    })?;
    let raw: TomlValue = toml::from_str(&content).map_err(|error| {
        ZtError::new(
            format!("could not parse config file {}: {error}", path.display()),
            2,
        )
    })?;
    let table = if let Some(defaults) = raw.get("defaults") {
        defaults
            .as_table()
            .ok_or_else(|| ZtError::new("config [defaults] must be a table", 2))?
    } else {
        raw.as_table()
            .ok_or_else(|| ZtError::new("config must be a table", 2))?
    };
    Ok(table
        .iter()
        .map(|(key, value)| (key.clone(), value.clone()))
        .collect())
}

fn env_config_values() -> ZtResult<BTreeMap<String, TomlValue>> {
    let mut values = BTreeMap::new();
    for (env_name, key) in [
        ("ZT_HOST", "host"),
        ("ZT_TRANSPORT", "transport"),
        ("ZT_PICKER", "picker"),
        ("ZT_REMOTE_PATH", "remote_path"),
        ("ZT_CONNECT_TIMEOUT", "connect_timeout"),
        ("ZT_SSH_OPTIONS", "ssh_options"),
        ("ZT_NO_INPUT", "no_input"),
    ] {
        if let Ok(value) = env::var(env_name) {
            values.insert(key.to_string(), TomlValue::String(value));
        }
    }
    Ok(values)
}

fn apply_values(config: &mut Config, values: &BTreeMap<String, TomlValue>) -> ZtResult<()> {
    for (key, value) in values {
        match key.as_str() {
            "host" => apply_host(config, value_as_str(value, key)?)?,
            "transport" => config.transport = Transport::parse(value_as_str(value, key)?)?,
            "picker" => config.picker = Picker::parse(value_as_str(value, key)?)?,
            "remote_path" => apply_remote_path(config, value_as_str(value, key)?)?,
            "connect_timeout" => config.connect_timeout = value_as_u64(value, key)?,
            "ssh_options" => config.ssh_options = value_as_string_list(value, key)?,
            "no_input" => config.no_input = value_as_bool(value, key)?,
            _ => return Err(ZtError::new(format!("unknown config key: {key}"), 2)),
        }
    }
    Ok(())
}

fn apply_host(config: &mut Config, value: &str) -> ZtResult<()> {
    if value.is_empty() {
        return Err(ZtError::new("host must be a non-empty string", 2));
    }
    config.host = value.to_string();
    Ok(())
}

fn apply_remote_path(config: &mut Config, value: &str) -> ZtResult<()> {
    if value.is_empty() {
        return Err(ZtError::new("remote_path must be a non-empty string", 2));
    }
    config.remote_path = value.to_string();
    Ok(())
}

fn value_as_str<'a>(value: &'a TomlValue, key: &str) -> ZtResult<&'a str> {
    value
        .as_str()
        .ok_or_else(|| ZtError::new(format!("{key} must be a string"), 2))
}

fn value_as_u64(value: &TomlValue, key: &str) -> ZtResult<u64> {
    if let Some(integer) = value.as_integer()
        && integer >= 0
    {
        return Ok(integer as u64);
    }
    if let Some(text) = value.as_str() {
        return text
            .parse::<u64>()
            .map_err(|_| ZtError::new(format!("{key} must be an integer"), 2));
    }
    Err(ZtError::new(format!("{key} must be an integer"), 2))
}

fn value_as_bool(value: &TomlValue, key: &str) -> ZtResult<bool> {
    if let Some(boolean) = value.as_bool() {
        return Ok(boolean);
    }
    if let Some(text) = value.as_str() {
        return match text.trim().to_ascii_lowercase().as_str() {
            "1" | "true" | "yes" | "on" => Ok(true),
            "0" | "false" | "no" | "off" => Ok(false),
            _ => Err(ZtError::new(format!("{key} must be a boolean"), 2)),
        };
    }
    Err(ZtError::new(format!("{key} must be a boolean"), 2))
}

fn value_as_string_list(value: &TomlValue, key: &str) -> ZtResult<Vec<String>> {
    if let Some(text) = value.as_str() {
        return Ok(text
            .split(',')
            .filter(|item| !item.is_empty())
            .map(ToString::to_string)
            .collect());
    }
    if let Some(array) = value.as_array() {
        let mut values = Vec::new();
        for item in array {
            values.push(
                item.as_str()
                    .ok_or_else(|| ZtError::new(format!("{key} must be a string list"), 2))?
                    .to_string(),
            );
        }
        return Ok(values);
    }
    Err(ZtError::new(format!("{key} must be a string list"), 2))
}

fn config_json(config: &Config) -> serde_json::Value {
    json!({
        "host": config.host,
        "transport": config.transport.as_str(),
        "picker": config.picker.as_str(),
        "remote_path": config.remote_path,
        "connect_timeout": config.connect_timeout,
        "ssh_options": config.ssh_options,
        "no_input": config.no_input,
        "config_path": config.config_path.display().to_string(),
        "config_loaded": config.config_loaded,
    })
}

fn default_config_text() -> String {
    [
        "# zt configuration",
        "",
        "# Remote host used when --host/-H is not provided.",
        "host = \"tmm\"",
        "",
        "# Attach transport: \"ssh\" or \"mosh\".",
        "transport = \"ssh\"",
        "",
        "# Interactive picker: \"auto\", \"fzf\", \"prompt\", or \"none\".",
        "picker = \"auto\"",
        "",
        "connect_timeout = 10",
        "remote_path = \"/opt/homebrew/bin:/usr/local/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH\"",
        "ssh_options = []",
        "no_input = false",
        "",
    ]
    .join("\n")
}

fn config_command(config: &Config, args: &ConfigArgs) -> ZtResult<i32> {
    match args
        .command
        .as_ref()
        .unwrap_or(&ConfigCommand::Show(JsonArgs { json: false }))
    {
        ConfigCommand::Path => {
            println!("{}", config.config_path.display());
            Ok(0)
        }
        ConfigCommand::Show(args) => {
            if args.json {
                print_json(&config_json(config))?;
            } else {
                println!("host: {}", config.host);
                println!("transport: {}", config.transport.as_str());
                println!("picker: {}", config.picker.as_str());
                println!("remote_path: {}", config.remote_path);
                println!("connect_timeout: {}", config.connect_timeout);
                println!("ssh_options: {}", config.ssh_options.join(", "));
                println!("no_input: {}", config.no_input);
                println!("config_path: {}", config.config_path.display());
                println!("config_loaded: {}", config.config_loaded);
            }
            Ok(0)
        }
        ConfigCommand::Init(args) => {
            if config.config_path.exists() && !args.force {
                return Err(ZtError::new(
                    format!(
                        "config already exists: {} (use --force to overwrite)",
                        config.config_path.display()
                    ),
                    2,
                ));
            }
            if let Some(parent) = config.config_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(&config.config_path, default_config_text())?;
            println!("{}", config.config_path.display());
            Ok(0)
        }
    }
}

fn remote_cmd(config: &Config, command: &str) -> String {
    format!("PATH={}; {command}", config.remote_path)
}

fn ssh_argv(config: &Config, batch: bool, tty: bool) -> Vec<String> {
    let mut args = vec!["ssh".to_string()];
    if tty {
        args.push("-t".to_string());
    }
    if batch {
        args.extend(["-o".to_string(), "BatchMode=yes".to_string()]);
    }
    if config.connect_timeout > 0 {
        args.extend([
            "-o".to_string(),
            format!("ConnectTimeout={}", config.connect_timeout),
        ]);
    }
    for option in &config.ssh_options {
        args.extend(["-o".to_string(), option.clone()]);
    }
    args.push(config.host.clone());
    args
}

fn run_remote(config: &Config, command: &str, batch: bool) -> ZtResult<Output> {
    let remote = remote_cmd(config, command);
    let argv = ssh_argv(config, batch, false);
    Command::new(&argv[0])
        .args(&argv[1..])
        .arg(remote)
        .output()
        .map_err(|error| ZtError::new(format!("ssh failed: {error}"), 1))
}

fn remote_error(output: &Output, action: &str) -> ZtError {
    let detail = output_text(output);
    ZtError::new(
        format!(
            "{action} failed on remote host: {}",
            if detail.trim().is_empty() {
                format!("exit {}", output.status.code().unwrap_or(1))
            } else {
                detail.trim().to_string()
            }
        ),
        output.status.code().unwrap_or(1),
    )
}

fn output_text(output: &Output) -> String {
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    [stdout.trim(), stderr.trim()]
        .into_iter()
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}

fn output_stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).trim().to_string()
}

fn output_stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).trim().to_string()
}

fn print_json(value: &serde_json::Value) -> ZtResult<()> {
    println!(
        "{}",
        serde_json::to_string(value).map_err(|error| ZtError::new(error.to_string(), 1))?
    );
    Ok(())
}

fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }
    if value
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || b"@%_+=:,./-".contains(&byte))
    {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn print_command(argv: &[String]) {
    println!(
        "{}",
        argv.iter()
            .map(|part| shell_quote(part))
            .collect::<Vec<_>>()
            .join(" ")
    );
}

fn command_status(argv: &[String]) -> ZtResult<i32> {
    let status = Command::new(&argv[0]).args(&argv[1..]).status()?;
    Ok(status.code().unwrap_or(1))
}

fn command_output(argv: &[String]) -> ZtResult<Output> {
    Command::new(&argv[0])
        .args(&argv[1..])
        .output()
        .map_err(ZtError::from)
}

fn slugify(value: &str) -> String {
    let mut slug = String::new();
    let mut last_dash = false;
    for character in value.chars().flat_map(|character| character.to_lowercase()) {
        if character.is_ascii_alphanumeric() {
            slug.push(character);
            last_dash = false;
        } else if !last_dash && !slug.is_empty() {
            slug.push('-');
            last_dash = true;
        }
    }
    while slug.ends_with('-') {
        slug.pop();
    }
    if slug.is_empty() {
        "zt".to_string()
    } else {
        slug
    }
}

fn auto_session_name(scope: &str, host: Option<&str>) -> String {
    let base = if scope == "local" {
        "mb"
    } else {
        host.unwrap_or("remote")
    };
    let random = random_suffix();
    format!("{}-{}-{random}", slugify(base), utc_timestamp())
}

fn utc_timestamp() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    let seconds = now.as_secs() as i64;
    let days = seconds.div_euclid(86_400);
    let second_of_day = seconds.rem_euclid(86_400);
    let (year, month, day) = civil_from_days(days);
    let hour = second_of_day / 3_600;
    let minute = (second_of_day % 3_600) / 60;
    let second = second_of_day % 60;
    format!("{year:04}{month:02}{day:02}-{hour:02}{minute:02}{second:02}")
}

fn civil_from_days(days_since_unix_epoch: i64) -> (i64, i64, i64) {
    let z = days_since_unix_epoch + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 }.div_euclid(146_097);
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096).div_euclid(365);
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2).div_euclid(153);
    let day = doy - (153 * mp + 2).div_euclid(5) + 1;
    let month = mp + if mp < 10 { 3 } else { -9 };
    let year = year + if month <= 2 { 1 } else { 0 };
    (year, month, day)
}

fn random_suffix() -> String {
    let mut bytes = [0_u8; 3];
    if fs::File::open("/dev/urandom")
        .and_then(|mut file| file.read_exact(&mut bytes))
        .is_ok()
    {
        return bytes
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
    }

    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or_default();
    let value = (nanos ^ std::process::id() as u128) & 0xffffff;
    format!("{value:06x}")
}

fn resolve_session_name(session: &str, auto: bool, scope: &str, host: Option<&str>) -> String {
    if auto || matches!(session, "" | "-" | "auto" | "new") {
        auto_session_name(scope, host)
    } else {
        session.to_string()
    }
}

fn list_sessions(config: &Config, reverse: bool) -> ZtResult<Vec<String>> {
    let mut command = "zellij list-sessions --short --no-formatting".to_string();
    if reverse {
        command.push_str(" --reverse");
    }
    let output = run_remote(config, &command, true)?;
    let combined = output_text(&output);
    if combined.contains("No active zellij sessions found") {
        return Ok(Vec::new());
    }
    if !output.status.success() {
        return Err(remote_error(&output, "list sessions"));
    }
    Ok(combined
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.contains("No active zellij sessions found"))
        .map(ToString::to_string)
        .collect())
}

fn filter_sessions(
    sessions: Vec<String>,
    prefix: Option<&str>,
    contains: Option<&str>,
) -> Vec<String> {
    sessions
        .into_iter()
        .filter(|session| prefix.is_none_or(|prefix| session.starts_with(prefix)))
        .filter(|session| contains.is_none_or(|contains| session.contains(contains)))
        .collect()
}

fn session_exists(config: &Config, session: &str) -> ZtResult<bool> {
    Ok(list_sessions(config, false)?
        .iter()
        .any(|item| item == session))
}

fn ensure_session(
    config: &Config,
    session: &str,
    json_output: bool,
    print_only: bool,
) -> ZtResult<i32> {
    let command = remote_cmd(
        config,
        &format!("zellij attach --create-background {}", shell_quote(session)),
    );
    let mut argv = ssh_argv(config, true, false);
    argv.push(command);

    if print_only {
        print_command(&argv);
        return Ok(0);
    }

    let output = command_output(&argv)?;
    if json_output {
        print_json(&json!({
            "host": config.host,
            "session": session,
            "ensured": output.status.success(),
            "stdout": output_stdout(&output),
            "stderr": output_stderr(&output),
        }))?;
    } else {
        io::stdout().write_all(&output.stdout)?;
        if output.status.success() && output.stdout.is_empty() {
            println!("{session}");
        }
        if !output.status.success() {
            io::stderr().write_all(&output.stderr)?;
        }
    }
    Ok(output.status.code().unwrap_or(1))
}

fn attach(
    config: &Config,
    session: &str,
    create: bool,
    background: bool,
    json_output: bool,
    print_only: bool,
) -> ZtResult<i32> {
    if background {
        return ensure_session(config, session, json_output, print_only);
    }

    let flags = if create { " --create" } else { "" };
    let command = remote_cmd(
        config,
        &format!("exec zellij attach{flags} {}", shell_quote(session)),
    );
    let argv = if config.transport == Transport::Mosh {
        vec![
            "mosh".to_string(),
            config.host.clone(),
            "--".to_string(),
            "sh".to_string(),
            "-lc".to_string(),
            command,
        ]
    } else {
        let mut args = ssh_argv(config, false, true);
        args.push(command);
        args
    };

    if print_only {
        print_command(&argv);
        return Ok(0);
    }
    if json_output {
        print_json(&json!({
            "host": config.host,
            "session": session,
            "attached": false,
            "command": argv.iter().map(|part| shell_quote(part)).collect::<Vec<_>>().join(" "),
        }))?;
        return Ok(0);
    }
    command_status(&argv)
}

fn attach_local(
    session: &str,
    create: bool,
    background: bool,
    json_output: bool,
    print_only: bool,
) -> ZtResult<i32> {
    let zellij = which::which("zellij").map_err(|_| {
        ZtError::new(
            "local zellij not found; run 'zt install --with-local-zellij'",
            127,
        )
    })?;
    let mut argv = vec![zellij.display().to_string(), "attach".to_string()];
    if background {
        argv.push("--create-background".to_string());
    } else if create {
        argv.push("--create".to_string());
    }
    argv.push(session.to_string());

    if print_only {
        print_command(&argv);
        return Ok(0);
    }
    if json_output {
        print_json(&json!({
            "scope": "local",
            "session": session,
            "attached": false,
            "command": argv.iter().map(|part| shell_quote(part)).collect::<Vec<_>>().join(" "),
        }))?;
        return Ok(0);
    }
    command_status(&argv)
}

fn is_missing_session_output(output: &str) -> bool {
    output.contains("No session named") || output.contains("not found")
}

fn kill_session(
    config: &Config,
    session: &str,
    missing_ok: bool,
    json_output: bool,
) -> ZtResult<i32> {
    if missing_ok && !session_exists(config, session)? {
        if json_output {
            print_json(
                &json!({"host": config.host, "session": session, "closed": false, "missing": true}),
            )?;
        }
        return Ok(0);
    }

    let output = run_remote(
        config,
        &format!("zellij kill-session {}", shell_quote(session)),
        true,
    )?;
    let missing = !output.status.success() && is_missing_session_output(&output_text(&output));
    if missing_ok && missing {
        if json_output {
            print_json(
                &json!({"host": config.host, "session": session, "closed": false, "missing": true}),
            )?;
        }
        return Ok(0);
    }

    if json_output {
        print_json(&json!({
            "host": config.host,
            "session": session,
            "closed": output.status.success(),
            "missing": missing,
            "stdout": output_stdout(&output),
            "stderr": output_stderr(&output),
        }))?;
    } else {
        io::stdout().write_all(&output.stdout)?;
        if !output.status.success() {
            io::stderr().write_all(&output.stderr)?;
        }
    }
    Ok(output.status.code().unwrap_or(1))
}

fn delete_session(
    config: &Config,
    session: &str,
    force: bool,
    missing_ok: bool,
    json_output: bool,
) -> ZtResult<i32> {
    let force_flag = if force { " --force" } else { "" };
    let output = run_remote(
        config,
        &format!("zellij delete-session{force_flag} {}", shell_quote(session)),
        true,
    )?;
    let missing = !output.status.success() && is_missing_session_output(&output_text(&output));
    if missing_ok && missing {
        if json_output {
            print_json(
                &json!({"host": config.host, "session": session, "deleted": false, "missing": true}),
            )?;
        }
        return Ok(0);
    }

    if json_output {
        print_json(&json!({
            "host": config.host,
            "session": session,
            "deleted": output.status.success(),
            "missing": missing,
            "force": force,
            "stdout": output_stdout(&output),
            "stderr": output_stderr(&output),
        }))?;
    } else {
        io::stdout().write_all(&output.stdout)?;
        if !output.status.success() {
            io::stderr().write_all(&output.stderr)?;
        }
    }
    Ok(output.status.code().unwrap_or(1))
}

fn choose_with_fzf(items: &[String]) -> Option<String> {
    if !io::stdin().is_terminal() || !io::stdout().is_terminal() || which::which("fzf").is_err() {
        return None;
    }
    let mut child = Command::new("fzf")
        .args(["--prompt", "zellij> ", "--height", "40%", "--reverse"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .ok()?;
    if let Some(stdin) = child.stdin.as_mut() {
        let _ = writeln!(stdin, "{}", items.join("\n"));
    }
    let output = child.wait_with_output().ok()?;
    if !output.status.success() {
        return Some(String::new());
    }
    Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn prompt_choice(sessions: &[String]) -> ZtResult<String> {
    if sessions.is_empty() {
        return prompt_new_name();
    }
    for (index, session) in sessions.iter().enumerate() {
        println!("{:2}. {}", index + 1, session);
    }
    println!("{:2}. {NEW_MARKER}", sessions.len() + 1);

    print!("session> ");
    io::stdout().flush()?;
    let mut answer = String::new();
    io::stdin().read_line(&mut answer)?;
    let answer = answer.trim();
    if answer.is_empty() {
        return Ok(String::new());
    }
    if let Ok(choice) = answer.parse::<usize>() {
        if (1..=sessions.len()).contains(&choice) {
            return Ok(sessions[choice - 1].clone());
        }
        if choice == sessions.len() + 1 {
            return prompt_new_name();
        }
    }
    Ok(answer.to_string())
}

fn prompt_new_name() -> ZtResult<String> {
    print!("new session name [main]> ");
    io::stdout().flush()?;
    let mut name = String::new();
    io::stdin().read_line(&mut name)?;
    let name = name.trim();
    Ok(if name.is_empty() {
        "main".to_string()
    } else {
        name.to_string()
    })
}

fn browse(config: &Config) -> ZtResult<i32> {
    if config.no_input || !io::stdin().is_terminal() || !io::stdout().is_terminal() {
        return Err(ZtError::new(
            "browse requires an interactive terminal; use 'zt list', 'zt ensure SESSION', or 'zt attach SESSION'",
            2,
        ));
    }
    if config.picker == Picker::None {
        return Err(ZtError::new(
            "browse is disabled because picker is set to none",
            2,
        ));
    }

    let sessions = list_sessions(config, false)?;
    let mut choices = vec![NEW_MARKER.to_string()];
    choices.extend(sessions.iter().cloned());
    let mut choice = if matches!(config.picker, Picker::Auto | Picker::Fzf) {
        choose_with_fzf(&choices)
    } else {
        None
    };
    if choice.is_none() && config.picker == Picker::Fzf {
        return Err(ZtError::new(
            "picker is set to fzf, but fzf is unavailable or not attached to a terminal",
            2,
        ));
    }
    if choice.is_none() {
        choice = Some(prompt_choice(&sessions)?);
    }
    let mut choice = choice.unwrap_or_default();
    if choice.is_empty() {
        return Ok(130);
    }
    if choice == NEW_MARKER {
        choice = prompt_new_name()?;
    }
    attach(config, &choice, true, false, false, false)
}

fn local_tool_status(tool: &str) -> ToolStatus {
    let Ok(path) = which::which(tool) else {
        return ToolStatus {
            present: false,
            path: None,
            version: None,
        };
    };
    let version_args = match tool {
        "ssh" | "tmux" => vec![tool.to_string(), "-V".to_string()],
        _ => vec![tool.to_string(), "--version".to_string()],
    };
    let version = command_output(&version_args).ok().and_then(|output| {
        let text = output_text(&output);
        text.lines().next().map(ToString::to_string)
    });
    ToolStatus {
        present: true,
        path: Some(path.display().to_string()),
        version,
    }
}

fn remote_tool_status(config: &Config) -> ZtResult<(serde_json::Value, Option<String>)> {
    let script = r#"
printf 'hostname\t%s\n' "$(hostname 2>/dev/null || uname -n)"
for tool in zellij tmux mosh; do
  tool_path=$(command -v "$tool" 2>/dev/null || true)
  if [ -z "$tool_path" ]; then
    printf 'tool\t%s\t\t\n' "$tool"
    continue
  fi
  case "$tool" in
    tmux) version=$("$tool" -V 2>&1 | sed -n '1p') ;;
    *) version=$("$tool" --version 2>&1 | sed -n '1p') ;;
  esac
  printf 'tool\t%s\t%s\t%s\n' "$tool" "$tool_path" "$version"
done
"#;
    let output = run_remote(config, script, true)?;
    let mut hostname = serde_json::Value::Null;
    let mut tools = serde_json::Map::new();
    if !output.status.success() {
        return Ok((
            json!({"hostname": null, "tools": {}}),
            Some(output_text(&output)),
        ));
    }

    for line in String::from_utf8_lossy(&output.stdout).lines() {
        let parts = line.split('\t').collect::<Vec<_>>();
        if parts.is_empty() {
            continue;
        }
        if parts[0] == "hostname" && parts.len() >= 2 {
            hostname = json!(parts[1]);
        } else if parts[0] == "tool" && parts.len() >= 4 {
            tools.insert(
                parts[1].to_string(),
                json!({
                    "present": !parts[2].is_empty(),
                    "path": if parts[2].is_empty() { serde_json::Value::Null } else { json!(parts[2]) },
                    "version": if parts[3].is_empty() { serde_json::Value::Null } else { json!(parts[3]) },
                }),
            );
        }
    }
    Ok((json!({"hostname": hostname, "tools": tools}), None))
}

fn status(config: &Config, json_output: bool) -> ZtResult<i32> {
    let local = ["ssh", "mosh", "zellij", "fzf"]
        .into_iter()
        .map(|tool| (tool.to_string(), local_tool_status(tool)))
        .collect::<BTreeMap<_, _>>();
    let (remote, remote_error_message) = remote_tool_status(config)?;
    let remote_tools = remote
        .get("tools")
        .and_then(|tools| tools.as_object())
        .cloned()
        .unwrap_or_default();
    let remote_zellij = remote_tools
        .get("zellij")
        .and_then(|tool| tool.get("present"))
        .and_then(|present| present.as_bool())
        .unwrap_or(false);
    let remote_mosh = remote_tools
        .get("mosh")
        .and_then(|tool| tool.get("present"))
        .and_then(|present| present.as_bool())
        .unwrap_or(false);
    let local_ssh = local.get("ssh").is_some_and(|tool| tool.present);
    let local_mosh = local.get("mosh").is_some_and(|tool| tool.present);
    let ok = local_ssh
        && remote_zellij
        && (config.transport != Transport::Mosh || (local_mosh && remote_mosh))
        && remote_error_message.is_none();

    let data = json!({
        "ok": ok,
        "host": config.host,
        "transport": config.transport.as_str(),
        "picker": config.picker.as_str(),
        "connect_timeout": config.connect_timeout,
        "config_path": config.config_path.display().to_string(),
        "config_loaded": config.config_loaded,
        "local": local,
        "remote": remote,
        "remote_error": remote_error_message,
    });

    if json_output {
        print_json(&data)?;
    } else {
        println!("host: {}", config.host);
        println!("transport: {}", config.transport.as_str());
        println!("picker: {}", config.picker.as_str());
        println!(
            "config: {} ({})",
            config.config_path.display(),
            if config.config_loaded {
                "loaded"
            } else {
                "missing"
            }
        );
        if let Some(hostname) = data
            .get("remote")
            .and_then(|remote| remote.get("hostname"))
            .and_then(|hostname| hostname.as_str())
        {
            println!("remote hostname: {hostname}");
        }
        if let Some(message) = data.get("remote_error").and_then(|value| value.as_str()) {
            eprintln!("remote error: {message}");
        }
        println!("local:");
        for (tool, info) in &local {
            if info.present {
                println!(
                    "  {tool}: {} ({})",
                    info.path.as_deref().unwrap_or(""),
                    info.version.as_deref().unwrap_or("")
                );
            } else {
                println!("  {tool}: missing");
            }
        }
        println!("remote:");
        for (tool, info) in &remote_tools {
            let present = info
                .get("present")
                .and_then(|value| value.as_bool())
                .unwrap_or(false);
            if present {
                println!(
                    "  {tool}: {} ({})",
                    info.get("path")
                        .and_then(|value| value.as_str())
                        .unwrap_or(""),
                    info.get("version")
                        .and_then(|value| value.as_str())
                        .unwrap_or("")
                );
            } else {
                println!("  {tool}: missing");
            }
        }
    }
    Ok(if ok { 0 } else { 1 })
}

fn detect_local_package_manager() -> Option<String> {
    for manager in package_managers() {
        if which::which(manager).is_ok() {
            return Some(manager.to_string());
        }
    }
    None
}

fn detect_remote_package_manager(config: &Config) -> ZtResult<Option<String>> {
    let managers = package_managers()
        .iter()
        .map(|manager| shell_quote(manager))
        .collect::<Vec<_>>()
        .join(" ");
    let command = format!(
        "for manager in {managers}; do command -v \"$manager\" >/dev/null 2>&1 && printf \"%s\\n\" \"$manager\" && exit 0; done; exit 1"
    );
    let output = run_remote(config, &command, true)?;
    if !output.status.success() {
        return Ok(None);
    }
    Ok(String::from_utf8_lossy(&output.stdout)
        .lines()
        .next()
        .map(|line| line.trim().to_string())
        .filter(|line| !line.is_empty()))
}

fn package_managers() -> [&'static str; 5] {
    ["brew", "apt-get", "dnf", "pacman", "apk"]
}

fn local_missing_tools(tools: &[String]) -> Vec<String> {
    tools
        .iter()
        .filter(|tool| which::which(tool).is_err())
        .cloned()
        .collect()
}

fn remote_missing_tools(config: &Config, tools: &[String]) -> ZtResult<Vec<String>> {
    if tools.is_empty() {
        return Ok(Vec::new());
    }
    let tool_args = tools
        .iter()
        .map(|tool| shell_quote(tool))
        .collect::<Vec<_>>()
        .join(" ");
    let command = format!(
        "for tool in {tool_args}; do command -v \"$tool\" >/dev/null 2>&1 || printf \"%s\\n\" \"$tool\"; done"
    );
    let output = run_remote(config, &command, true)?;
    if !output.status.success() {
        return Err(remote_error(&output, "check remote dependencies"));
    }
    Ok(String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(ToString::to_string)
        .collect())
}

fn package_install_command(package_manager: &str, packages: &[String]) -> ZtResult<String> {
    let package_args = packages
        .iter()
        .map(|package| shell_quote(package))
        .collect::<Vec<_>>()
        .join(" ");
    match package_manager {
        "brew" => Ok(format!("brew install {package_args}")),
        "apt-get" => Ok(format!(
            "sudo apt-get update && sudo apt-get install -y {package_args}"
        )),
        "dnf" => Ok(format!("sudo dnf install -y {package_args}")),
        "pacman" => Ok(format!(
            "sudo pacman -S --needed --noconfirm {package_args}"
        )),
        "apk" => Ok(format!("sudo apk add {package_args}")),
        _ => Err(ZtError::new(
            format!("unsupported package manager: {package_manager}"),
            2,
        )),
    }
}

fn install_tool_targets(config: &Config, args: &InstallArgs) -> (Vec<String>, Vec<String>) {
    let mut local = BTreeSet::new();
    let mut remote = BTreeSet::from(["zellij".to_string()]);

    if !args.no_fzf && matches!(config.picker, Picker::Auto | Picker::Fzf) {
        local.insert("fzf".to_string());
    }
    if args.with_mosh || config.transport == Transport::Mosh {
        local.insert("mosh".to_string());
        remote.insert("mosh".to_string());
    }
    if args.with_tmux {
        remote.insert("tmux".to_string());
    }
    if args.with_local_zellij {
        local.insert("zellij".to_string());
    }

    (local.into_iter().collect(), remote.into_iter().collect())
}

fn install_scopes(args: &InstallArgs) -> Vec<String> {
    if args.local_only {
        vec!["local".to_string()]
    } else if args.remote_only {
        vec!["remote".to_string()]
    } else {
        vec!["local".to_string(), "remote".to_string()]
    }
}

fn build_install_plan(config: &Config, args: &InstallArgs) -> ZtResult<InstallPlan> {
    let scopes = install_scopes(args);
    let (local_targets, remote_targets) = install_tool_targets(config, args);
    let mut plan = Vec::new();
    let mut installed = BTreeMap::from([
        ("local".to_string(), Vec::new()),
        ("remote".to_string(), Vec::new()),
    ]);
    let mut missing = installed.clone();
    let mut package_managers =
        BTreeMap::from([("local".to_string(), None), ("remote".to_string(), None)]);
    let targets = BTreeMap::from([
        ("local".to_string(), local_targets.clone()),
        ("remote".to_string(), remote_targets.clone()),
    ]);

    if scopes.iter().any(|scope| scope == "local") && !local_targets.is_empty() {
        let local_missing = local_missing_tools(&local_targets);
        let local_installed = local_targets
            .iter()
            .filter(|tool| !local_missing.contains(tool))
            .cloned()
            .collect::<Vec<_>>();
        installed.insert("local".to_string(), local_installed);
        missing.insert("local".to_string(), local_missing.clone());
        if !local_missing.is_empty() {
            let manager = detect_local_package_manager().ok_or_else(|| {
                ZtError::new(
                    "no supported local package manager found (expected brew, apt-get, dnf, pacman, or apk)",
                    2,
                )
            })?;
            package_managers.insert("local".to_string(), Some(manager.clone()));
            plan.push(InstallEntry {
                scope: "local".to_string(),
                package_manager: manager.clone(),
                packages: local_missing.clone(),
                command: package_install_command(&manager, &local_missing)?,
            });
        }
    }

    if scopes.iter().any(|scope| scope == "remote") && !remote_targets.is_empty() {
        let remote_missing = remote_missing_tools(config, &remote_targets)?;
        let remote_installed = remote_targets
            .iter()
            .filter(|tool| !remote_missing.contains(tool))
            .cloned()
            .collect::<Vec<_>>();
        installed.insert("remote".to_string(), remote_installed);
        missing.insert("remote".to_string(), remote_missing.clone());
        if !remote_missing.is_empty() {
            let manager = detect_remote_package_manager(config)?.ok_or_else(|| {
                ZtError::new(
                    format!(
                        "no supported package manager found on {} (expected brew, apt-get, dnf, pacman, or apk)",
                        config.host
                    ),
                    2,
                )
            })?;
            package_managers.insert("remote".to_string(), Some(manager.clone()));
            plan.push(InstallEntry {
                scope: "remote".to_string(),
                package_manager: manager.clone(),
                packages: remote_missing.clone(),
                command: package_install_command(&manager, &remote_missing)?,
            });
        }
    }

    Ok(InstallPlan {
        host: config.host.clone(),
        transport: config.transport.as_str().to_string(),
        picker: config.picker.as_str().to_string(),
        scopes,
        targets,
        installed,
        missing,
        package_managers,
        plan,
    })
}

fn confirm_install(plan: &[InstallEntry], yes: bool, no_input: bool) -> ZtResult<()> {
    if plan.is_empty() || yes {
        return Ok(());
    }
    if no_input || !io::stdin().is_terminal() {
        return Err(ZtError::new(
            "install requires --yes in noninteractive mode",
            2,
        ));
    }
    println!("zt will run:");
    for entry in plan {
        println!("  [{}] {}", entry.scope, entry.command);
    }
    print!("install missing dependencies? [y/N] ");
    io::stdout().flush()?;
    let mut answer = String::new();
    io::stdin().read_line(&mut answer)?;
    if !matches!(answer.trim().to_ascii_lowercase().as_str(), "y" | "yes") {
        return Err(ZtError::new("install cancelled", 130));
    }
    Ok(())
}

fn run_install_entry(
    config: &Config,
    entry: &InstallEntry,
    json_output: bool,
) -> ZtResult<serde_json::Value> {
    if entry.scope == "local" {
        if json_output {
            let output = Command::new("sh")
                .arg("-lc")
                .arg(&entry.command)
                .output()
                .map_err(ZtError::from)?;
            return Ok(json!({
                "scope": entry.scope,
                "command": entry.command,
                "returncode": output.status.code().unwrap_or(1),
                "stdout": output_stdout(&output),
                "stderr": output_stderr(&output),
            }));
        }
        let status = Command::new("sh")
            .arg("-lc")
            .arg(&entry.command)
            .status()
            .map_err(ZtError::from)?;
        return Ok(json!({
            "scope": entry.scope,
            "command": entry.command,
            "returncode": status.code().unwrap_or(1),
        }));
    }

    let mut argv = ssh_argv(config, json_output, !json_output);
    argv.push(remote_cmd(config, &entry.command));
    if json_output {
        let output = command_output(&argv)?;
        return Ok(json!({
            "scope": entry.scope,
            "command": argv.iter().map(|part| shell_quote(part)).collect::<Vec<_>>().join(" "),
            "returncode": output.status.code().unwrap_or(1),
            "stdout": output_stdout(&output),
            "stderr": output_stderr(&output),
        }));
    }
    let returncode = command_status(&argv)?;
    Ok(json!({
        "scope": entry.scope,
        "command": argv.iter().map(|part| shell_quote(part)).collect::<Vec<_>>().join(" "),
        "returncode": returncode,
    }))
}

fn install_dependencies(config: &Config, args: &InstallArgs) -> ZtResult<i32> {
    let plan = build_install_plan(config, args)?;
    if args.dry_run {
        if args.json {
            let mut data =
                serde_json::to_value(&plan).map_err(|error| ZtError::new(error.to_string(), 1))?;
            data["dry_run"] = json!(true);
            print_json(&data)?;
        } else if plan.plan.is_empty() {
            println!("all selected dependencies are already installed");
        } else {
            for entry in &plan.plan {
                println!("[{}] {}", entry.scope, entry.command);
            }
        }
        return Ok(0);
    }

    confirm_install(&plan.plan, args.yes, config.no_input)?;
    let mut results = Vec::new();
    let mut failed = false;
    for entry in &plan.plan {
        let result = run_install_entry(config, entry, args.json)?;
        let returncode = result
            .get("returncode")
            .and_then(|value| value.as_i64())
            .unwrap_or(1);
        failed |= returncode != 0;
        results.push(result);
    }

    if args.json {
        let mut data =
            serde_json::to_value(&plan).map_err(|error| ZtError::new(error.to_string(), 1))?;
        data["dry_run"] = json!(false);
        data["results"] = json!(results);
        data["ok"] = json!(!failed);
        print_json(&data)?;
    } else if plan.plan.is_empty() {
        println!("all selected dependencies are already installed");
    } else if failed {
        eprintln!("one or more install commands failed");
    }
    Ok(if failed { 1 } else { 0 })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shortcut_normalizes_unknown_command_to_attach() {
        assert_eq!(
            normalize_shortcut(vec!["--mosh".into(), "work".into()]),
            vec!["--mosh", "attach", "work"]
        );
    }

    #[test]
    fn shortcut_keeps_known_commands() {
        assert_eq!(
            normalize_shortcut(vec!["remote".into(), "work".into()]),
            vec!["remote", "work"]
        );
    }

    #[test]
    fn slugify_strips_to_safe_name() {
        assert_eq!(slugify("TMM Host!"), "tmm-host");
    }

    #[test]
    fn auto_marker_resolves() {
        let session = resolve_session_name("auto", false, "remote", Some("tmm"));
        assert!(session.starts_with("tmm-"));
    }

    #[test]
    fn random_suffix_is_short_hex() {
        let suffix = random_suffix();
        assert_eq!(suffix.len(), 6);
        assert!(
            suffix
                .chars()
                .all(|character| character.is_ascii_hexdigit())
        );
    }
}
